steps:
  # Maven build
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['install']
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/psychic-rush-331522/valpower/valpower:latest', '.' ]
  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/psychic-rush-331522/valpower/valpower:latest' ]